# Exercise 1: NumPy: Create an array with values ranging from 12 to 38

In [1]:
import numpy as np
a=np.array(range(12,38))
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


## Exercise 2: Add a border around an existing array¶
# Hint: np.pad()


In [6]:
a1=np.ones((3,3))

print(a1)
a2=np.pad(a1,pad_width=1,mode='constant')
print(a2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# Exercise 3: Convert a list and tuple into arrays

In [12]:
list1 = [1,2,3,4,5,6,7,8]
a3=np.asarray(list1)
print('list to array:\n',a3)

tuple1=([8,4,6],[1,2,3])
a4 = np.asarray(tuple1)
print('tuple to array:\n',a4)

list to array:
 [1 2 3 4 5 6 7 8]
tuple to array:
 [[8 4 6]
 [1 2 3]]


# Exercise 4: Convert the values of Centigrade degrees into Fahrenheit degrees

In [14]:
fdeg = np.array([0,12,45.21,34,99.91])
print("Values in Fahrenheit degrees:\n",fdeg)
cdeg = (5*(fdeg - 32))/9
print("Values in Centrigrade degrees:\n",cdeg)

Values in Fahrenheit degrees:
 [ 0.   12.   45.21 34.   99.91]
Values in Centrigrade degrees:
 [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


# Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [21]:
#Size of the array: 3 Length of one array element in bytes: 8 Total bytes consumed by the elements of the array: 24
a5=np.array((1,2,3),dtype=np.float)
print('size of the array:',a5.size)
print('length of one array element in bytes:',a5.itemsize)
print('total bytes consumed by the array:',a5.nbytes)

size of the array: 3
length of one array element in bytes: 8
total bytes consumed by the array: 24


# Exercise 6: Get the unique elements of an array

In [27]:
a6 = np.array([10,10,20,20,30,30])
print('original array:',a6)
print('unique elements of the array:',np.unique(a6))

a7=np.array([[1,1],[2,3]])
print('originala array:\n',a7)
print('unique elements of the array:\n ',np.unique(a7))

original array: [10 10 20 20 30 30]
unique elements of the array: [10 20 30]
originala array:
 [[1 1]
 [2 3]]
unique elements of the array:
  [1 2 3]


# Exercise 7: Change the dimension of an array

In [35]:
a8=np.array((1,2,3,4,5,6,7,8,9))
print(a8)
print("change the shape of array to (3, 3) -> 3 rows and 3 columns:\n",a8.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
change the shape of array to (3, 3) -> 3 rows and 3 columns:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [38]:
a9 = np.linspace(2.5,6.5,30)
print(a9)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


## Exercise 9: Convert 1-D arrays as columns into a 2-D array

In [56]:
array1 = np.array([10,20,30])
array2 = np.array([40,50,60])
print(array1)
print(array2)
#array3 = np.concatenate((array1,array2))
#print('convert the array to 2d:\n',array3.reshape(3,2))
array4 = np.stack((array1,array2),axis=1)
print(array4)

[10 20 30]
[40 50 60]
[[10 40]
 [20 50]
 [30 60]]


## Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

In [65]:
arr1 = np.zeros((5,5))
print(arr1)
arr2=np.arange(5)
print(arr2)
print('add both:\n',arr1+arr2)

arr1 += np.arange(5)
print('another way:\n',arr1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0 1 2 3 4]
add both:
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
another way:
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Exercise 11: Sum of all the multiples of 3 or 5 below 100

In [71]:
arr11 = np.array(range(1,100))
print(arr11)
list11 = []
sum=0
for i in arr11:
    if ((i%3==0) or (i%5==0)):
        list11.append(i)
        sum+=i

print(list11)
print(sum)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[3, 5, 6, 9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35, 36, 39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70, 72, 75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96, 99]
2318


## Exercise 12: Combine a one and a two dimensional array together and display their elements¶
Hint : np.nditer()

In [72]:
#example
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)

0
0
1
1
2
2
3
3


In [76]:
arr_1d = np.arange(4)
print(arr_1d)
arr_2d = np.arange(8).reshape(2,4)
print(arr_2d)
for i,j in np.nditer([arr_1d,arr_2d]):
    print(str(i)+":"+str(j))

[0 1 2 3]
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


# Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

In [79]:
arr13 = np.array([[[0.42436315,0.48558583,0.32924763],[0.7439979,0.58220701,0.38213418], [0.5097581,0.34528799,0.1563123 ]]])
print('original array:\n',arr13)
arr13[arr13>0.5] = 0.5
print(arr13)

original array:
 [[[0.42436315 0.48558583 0.32924763]
  [0.7439979  0.58220701 0.38213418]
  [0.5097581  0.34528799 0.1563123 ]]]
[[[0.42436315 0.48558583 0.32924763]
  [0.5        0.5        0.38213418]
  [0.5        0.34528799 0.1563123 ]]]


# Exercise 14: Add a new row to an empty numpy array

In [89]:
list14 = []
arr14 = np.array(list14)
print(arr14)
arr14 = np.append(arr14,[10,20,30])
print(arr14)
arr14 = np.vstack((arr14,[40,50,60]))
print(arr14)

[]
[10. 20. 30.]
[[10. 20. 30.]
 [40. 50. 60.]]


# Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis.

In [97]:
ar1 = np.array([[1],[2],[3]])
ar2 = np.array([[2],[3],[4]])
print("Original arrays:")
print(ar1)
print('\n')
print(ar2)
ar3 = np.vstack((ar1,ar2))
print('Sequence of arrays along a new axis:')
print(ar3)

Original arrays:
[[1]
 [2]
 [3]]


[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
